name: cake_shop
description: A beautiful cake shop app.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  google_fonts: ^8.1.0
  cached_network_image: ^3.3.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/